name: Create Documentation
on:
  push:
    branches:
      - master
jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Document
        run: |
          python -m pip install --upgrade pip
          pip install -r ./docs/requirements.txt
          sphinx-apidoc ./biosimulations_query -o ./docs/source/modules/
          sphinx-build ./docs/source/ ./docs/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: documentation
          COMMIT_MESSAGE: automatic documentation
          PULL_REQUEST_TITLE: Creation of documentation
