name: Format python code
on:
  push:
    branches:
      - master
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: autopep8
        uses: peter-evans/autopep8@v1.0.0
        with:
          args: --recursive --in-place --aggressive --aggressive .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: autopep8-patches
          COMMIT_MESSAGE: autopep8 action fixes
          PULL_REQUEST_TITLE: Fixes by autopep8 action
